### ISSUE TITLE
Cannot read properties of undefined (reading 'redirect_uris') at authenticate 

### ISSUE THREAD

**Issue by thiago-g-martins** [googleworkspace/node-samples#209]
# Summary

quickstart code for gmail is not running first authentication on linux. Credentials.json created properly and it is in the same folder. Code running is untouched.

Node v16.17.0
NPM v8.15.0
Operating System: Ubuntu 22.04.1 LTS              
Kernel: Linux 5.15.0-1017-gcp
Architecture: x86-64

Command:

node index.js

output:

TypeError: Cannot read properties of undefined (reading 'redirect_uris')
    at authenticate (/home/envioDeRelatorios/node_modules/@google-cloud/local-auth/build/src/index.js:50:15) at  authorize (/home/index.js:75:18)

Thank you all!

**Comment by thiago-g-martins** [comment]
For future reference to anyone that can have the same mistake, I created the wrong type of credentials. Did not created the desktop-app one as described here:
https://developers.google.com/workspace/guides/create-credentials#desktop-app
